// <auto-generated />
using System;
using Dogshouseservice.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dogshouseservice.API.Migrations
{
    [DbContext(typeof(DogsHouseServiceDbContext))]
    [Migration("20231013141351_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dogshouseservice.API.Models.Domain.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tail_length")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e16b336b-0797-47e2-ba77-04e7aef98f35"),
                            Color = "red&amber",
                            Name = "Neo",
                            Tail_length = 22,
                            Weight = 32
                        },
                        new
                        {
                            Id = new Guid("32369c97-b9a1-4810-8b64-1ab5922d8cd7"),
                            Color = "black&white",
                            Name = "Jessy",
                            Tail_length = 7,
                            Weight = 14
                        },
                        new
                        {
                            Id = new Guid("54c986fb-0d40-4e99-b6c7-a7134f55f081"),
                            Color = "brown&white",
                            Name = "Tom",
                            Tail_length = 12,
                            Weight = 41
                        },
                        new
                        {
                            Id = new Guid("284b3048-3da7-477f-93df-44ec48951399"),
                            Color = "grey",
                            Name = "Jerry",
                            Tail_length = 12,
                            Weight = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
